name : Install Oracle Java 7 on Ubunutu
desc : The recipe installs oracle jdk 7 on Ubunutu  
logo_url: https://raw.githubusercontent.com/tanmally/install-java-7/master/logo/Java7.png
tags:
    - java 7
    - oracle jdk
    - latest
    - Ubunutu
 
task:

  - name: Install Oracle Java 7
    cmd:
        - export DEBIAN_FRONTEND=noninteractive
        - echo oracle-java7-installer shared/accepted-oracle-license-v1-1 select true | debconf-set-selections
        - add-apt-repository -y ppa:webupd7team/java 
        - apt-get update
        - apt-get install -y oracle-java7-installer 
        - rm -rf /var/lib/apt/lists/*
        - rm -rf /var/cache/oracle-jdk7-installer        
        - apt-get clean
        # Set java env for all users
        - grep -q JAVA_HOME /etc/environment || echo 'JAVA_HOME="/usr/lib/jvm/java-7-oracle"' >> /etc/environment
